"""Add brought_forward and update carry_forward logic

Revision ID: 29de248662be
Revises: 10ee0f8411a7
Create Date: 2025-07-13 00:52:53.910942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29de248662be'
down_revision: Union[str, Sequence[str], None] = '10ee0f8411a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_periods', sa.Column('brought_forward', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_periods', 'brought_forward')
    # ### end Alembic commands ###
