"""change period use datetimes

Revision ID: c1a95150f01f
Revises: d67b070b9c01
Create Date: 2025-07-13 03:40:50.851647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1a95150f01f"
down_revision: Union[str, Sequence[str], None] = "d67b070b9c01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns
    op.add_column("budget_periods", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("budget_periods", sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True))

    # Migrate data from old columns to new columns
    op.execute(
        """
        UPDATE budget_periods
        SET started_at = start_date::timestamp,
            ended_at = end_date::timestamp
        """
    )

    # Make started_at NOT NULL if needed
    op.alter_column("budget_periods", "started_at", nullable=False)

    # Drop old columns
    op.drop_column("budget_periods", "end_date")
    op.drop_column("budget_periods", "start_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("budget_periods", sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False))
    op.add_column("budget_periods", sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column("budget_periods", "ended_at")
    op.drop_column("budget_periods", "started_at")
    # ### end Alembic commands ###
