"""add next and prev periods cols

Revision ID: 813f0b17389d
Revises: b5e8cac07da1
Create Date: 2025-07-14 05:03:05.829913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813f0b17389d'
down_revision: Union[str, Sequence[str], None] = 'b5e8cac07da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_periods', sa.Column('next_period_id', sa.UUID(), nullable=True))
    op.add_column('budget_periods', sa.Column('previous_period_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_budget_periods_next_period_id_budget_periods'), 'budget_periods', 'budget_periods', ['next_period_id'], ['id'])
    op.create_foreign_key(op.f('fk_budget_periods_previous_period_id_budget_periods'), 'budget_periods', 'budget_periods', ['previous_period_id'], ['id'])
    op.drop_constraint(op.f('payment_methods_name_key'), 'payment_methods', type_='unique')
    op.create_unique_constraint(op.f('uq_payment_methods_name'), 'payment_methods', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_payment_methods_name'), 'payment_methods', type_='unique')
    op.create_unique_constraint(op.f('payment_methods_name_key'), 'payment_methods', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_budget_periods_previous_period_id_budget_periods'), 'budget_periods', type_='foreignkey')
    op.drop_constraint(op.f('fk_budget_periods_next_period_id_budget_periods'), 'budget_periods', type_='foreignkey')
    op.drop_column('budget_periods', 'previous_period_id')
    op.drop_column('budget_periods', 'next_period_id')
    # ### end Alembic commands ###
