"""rename fields to transacted_at and carried_forward

Revision ID: b5e8cac07da1
Revises: c1a95150f01f
Create Date: 2025-07-13 08:24:26.473195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5e8cac07da1"
down_revision: Union[str, Sequence[str], None] = "c1a95150f01f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns (transacted_at initially nullable)
    op.add_column("budget_periods", sa.Column("carried_forward", sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column("transactions", sa.Column("transacted_at", sa.DateTime(timezone=True), nullable=True))

    # Migrate data from old columns to new columns
    op.execute(
        """
        UPDATE budget_periods
        SET carried_forward = carry_forward
        """
    )
    op.execute(
        """
        UPDATE transactions
        SET transacted_at = transaction_date::timestamp
        """
    )

    # Set transacted_at to NOT NULL after migration
    op.alter_column("transactions", "transacted_at", nullable=False)

    # Drop old columns
    op.drop_column("budget_periods", "carry_forward")
    op.drop_column("transactions", "transaction_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("transaction_date", sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column("transactions", "transacted_at")
    op.add_column(
        "budget_periods",
        sa.Column("carry_forward", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    )
    op.drop_column("budget_periods", "carried_forward")
    # ### end Alembic commands ###
