"""make period end_date nullable

Revision ID: d67b070b9c01
Revises: 29de248662be
Create Date: 2025-07-13 01:48:39.458791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67b070b9c01'
down_revision: Union[str, Sequence[str], None] = '29de248662be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_periods', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_periods', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
